name: Dependency Graph and Dependabot Scan

on:
  push:
    branches:
      - master

jobs:
  dependency_graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
        with:
          directory: "/"
          token: ${GITHUB_PAT}

