name: Malware Scanning

on:
  push:
    branches:
      - main
      - master

jobs:
  scan_repository:
    name: "Scan Virus on Repository"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - name: "Use Shared Action"
        uses: hpe-actions/malware-scanning@master
